### ISSUE TITLE
Reimport generator settings with a drag & drop

### ISSUE THREAD

**Issue by ypapouin** [ivantodorovich/odoo-icon#2]
It would be nice to be able to re-import a previously generated SVG.

All settings would be stored in the SVG as custom attributes with an oib (odoo-icon-builder) prefix (like inkscape does) :
```
<svg
    oib:version="1.0"
    oib:odoo-version="14.0"
    oib:color="#fdd835"
    oib:iconify-name="mdi:home"
    oib:size="0.5"
>
  ...
</svg>
```

When dropping a such file on the generator, if the attribute `oib:version` is detected then ask the user if he wants replace active settings with the ones stored into the file, else just replace the svg content as usual.

**Comment by ivantodorovich** [comment]
That's a great idea !

It shouldn't be hard to do.

For the export, the custom attributes could be added here: https://github.com/ivantodorovich/odoo-icon/blob/7289e874f67b0a75de10d6ba8b12e13a801d3c66/src/icon/icon.js#LL47C1-L47C1

For the import, somewhere in there https://github.com/ivantodorovich/odoo-icon/blob/7289e874f67b0a75de10d6ba8b12e13a801d3c66/src/App.js#L37-L40

The tricky case would be to re-import icons that aren't using an iconify icon (ie: a custom svg icon drag&dropped). We'd need to read the icon path from the file. But I'm ok to have this feature w/o support for this at the beggining

**Comment by ivantodorovich** [comment]
Exports implemented here:
- https://github.com/ivantodorovich/odoo-icon/pull/3

Still pending the imports, though
